### ISSUE TITLE
Not Python3 compatible.

### ISSUE THREAD

**Issue by markkness** [markkness/ColorPy#4]
ColorPy at present is only Python2.x, it would be better if Python3 was also supported.

Some culprits are old-style print statements, and some exception raising syntax.

**Comment by PanderMusubi** [comment]
Working on it

**Comment by PanderMusubi** [comment]
See https://github.com/markkness/ColorPy/pull/5

**Comment by markkness** [comment]
The current `master` is now hoped to be Python 3 compatible, though it has not been explicitly tested.

**Comment by markkness** [comment]
I just installed Python 3, and can confirm that the current `master` does run fine with it.

**Comment by markkness** [comment]
Closing this issue as this is now thought Python 3 compatible, and I have tools set up to keep it such.

**Comment by guillochon** [comment]
I was not able to get this to work with Python 3.5.1, I get an error when trying to import from `colorpy.ciexyz`:

    ImportError: No module named 'colormodels'

**Comment by avsparry** [comment]
i still have this error can anyone explain how to reinstall/update

**Comment by hiwigiwi** [comment]
bit of a hack, but the following fixes the `ImportError `for me [DISCLAIMER: i have very limited need for this package, so can not guarantee that this will not breaks other stuff, but the functions I relied on 'xyz_from_spectrum' and 'xyz_from_wavelength' work properly after the steps below]:

1. in ciexyz.py:

- replace `import colormodels` with `from . import colormodels`
- replace all occurences of the `xrange` function with the `range` function (the search and replace function of your editor should make this a breeze. there's about 10 instances)

2. in colormodels.py:
- there are 3 occurences of `raise` which make use of the python2 syntax, namely `raise ValueError, 'irgb_string_from_irgb(): Expecting 7 character string like #AB13D2'`. This needs to be updated to the python3 syntax `raise ValueError('irgb_string_from_irgb(): Expecting 7 character string like #AB13D2')`

save both files and stuff works...for now...
